from __future__ import annotations

import ast
import re
from dataclasses import dataclass, field

from app.equations.parser import DELAY_FUNCTIONS, SMOOTH_FUNCTIONS, parse_equation
from app.schemas.model import AuxNode, FlowNode, LookupNode, ModelDocument, StockNode
from app.validation.semantic import topological_order_for_transients


@dataclass(frozen=True)
class ExecutableNode:
    name: str
    node_type: str
    equation: str
    parsed_symbols: set[str]
    node_id: str


@dataclass(frozen=True)
class DelayStock:
    """Internal stock generated by expanding a delay function call."""
    name: str             # e.g. "__delay__my_var__1"
    input_expr: str       # expression for what feeds this stage
    delay_time_expr: str  # delay time per stage (e.g. "10" or "(T / 3)")


@dataclass(frozen=True)
class DelayFixedSpec:
    """Buffer-based pipeline delay (delay_fixed)."""
    name: str              # synthetic variable name for output
    input_expr: str        # expression to sample each step
    delay_time_expr: str   # delay time expression
    initial_expr: str      # initial output value expression


@dataclass(frozen=True)
class ExecutableModel:
    stock_nodes: list[StockNode]
    aux_nodes: list[AuxNode]
    flow_nodes: list[FlowNode]
    lookup_nodes: list[LookupNode]
    node_by_name: dict[str, object]
    transient_order: list[str]
    outputs: list[str]
    delay_stocks: list[DelayStock] = field(default_factory=list)
    delay_fixed_specs: list[DelayFixedSpec] = field(default_factory=list)



def _derive_stock_equations(model: ModelDocument) -> dict[str, str]:
    """Derive stock derivative equations from flow_link edges: sum(inflows) - sum(outflows)."""
    node_by_id: dict[str, object] = {}
    flow_ids: set[str] = set()
    for node in model.nodes:
        node_by_id[node.id] = node
        if isinstance(node, FlowNode):
            flow_ids.add(node.id)

    stock_eq: dict[str, str] = {}  # stock_id → equation
    inflows: dict[str, list[str]] = {}
    outflows: dict[str, list[str]] = {}

    for edge in model.edges:
        if edge.type != "flow_link":
            continue
        src = node_by_id.get(edge.source)
        tgt = node_by_id.get(edge.target)
        if src is None or tgt is None:
            continue
        # flow → stock: inflow to the stock
        if isinstance(src, FlowNode) and isinstance(tgt, StockNode):
            inflows.setdefault(tgt.id, []).append(src.name)
        # stock → flow: outflow from the stock
        if isinstance(src, StockNode) and isinstance(tgt, FlowNode):
            outflows.setdefault(src.id, []).append(tgt.name)

    for node in model.nodes:
        if not isinstance(node, StockNode):
            continue
        inf = inflows.get(node.id, [])
        outf = outflows.get(node.id, [])
        if not inf and not outf:
            # No flows connected — keep existing equation (e.g. '0')
            continue
        terms: list[str] = []
        for f in inf:
            terms.append(f)
        for f in outf:
            terms.append(f"-{f}")
        eq = terms[0]
        for t in terms[1:]:
            eq += f" - {t[1:]}" if t.startswith("-") else f" + {t}"
        stock_eq[node.id] = eq

    return stock_eq


# ---------------------------------------------------------------------------
# Delay expansion
# ---------------------------------------------------------------------------

def _ast_to_source(node: ast.AST) -> str:
    """Convert an AST node back to a Python expression string."""
    return ast.unparse(node)


def _find_delay_calls(equation: str) -> list[tuple[str, list[str], int, int]]:
    """Find delay function calls in an equation string.

    Returns list of (func_name, arg_sources, start_offset, end_offset).
    """
    try:
        tree = ast.parse(equation, mode="eval")
    except SyntaxError:
        return []

    results: list[tuple[str, list[str], int, int]] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Name):
            continue
        if node.func.id not in DELAY_FUNCTIONS and node.func.id not in SMOOTH_FUNCTIONS:
            continue
        arg_sources = [_ast_to_source(arg) for arg in node.args]
        results.append((node.func.id, arg_sources, node.col_offset, node.end_col_offset or 0))

    return results


def _expand_delays(
    var_name: str,
    equation: str,
) -> tuple[str, list[DelayStock]]:
    """Expand delay function calls in an equation into DelayStock entries.

    Returns (rewritten_equation, delay_stocks).
    """
    calls = _find_delay_calls(equation)
    if not calls:
        return equation, []

    all_delay_stocks: list[DelayStock] = []
    # Process calls in reverse offset order so string replacement doesn't shift positions
    calls_sorted = sorted(calls, key=lambda c: c[2], reverse=True)

    # Work on AST for reliable rewriting
    tree = ast.parse(equation, mode="eval")

    # Normalize smooth → delay aliases
    _SMOOTH_TO_DELAY = {"smooth": "delay1", "smooth3": "delay3"}

    call_idx = 0
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Name):
            continue
        if node.func.id not in DELAY_FUNCTIONS and node.func.id not in SMOOTH_FUNCTIONS:
            continue

        func_name = _SMOOTH_TO_DELAY.get(node.func.id, node.func.id)
        args = [_ast_to_source(arg) for arg in node.args]

        if func_name == "delay1":
            if len(args) < 2:
                continue
            n_stages = 1
            input_expr = args[0]
            delay_time = args[1]
        elif func_name == "delay3":
            if len(args) < 2:
                continue
            n_stages = 3
            input_expr = args[0]
            delay_time = args[1]
        elif func_name == "delayn":
            if len(args) < 3:
                continue
            n_stages = int(ast.literal_eval(args[2]))
            input_expr = args[0]
            delay_time = args[1]
        else:
            continue

        # Build per-stage delay time expression
        if n_stages == 1:
            stage_delay = delay_time
        else:
            stage_delay = f"(({delay_time}) / {n_stages})"

        stocks: list[DelayStock] = []
        prefix = f"__delay__{var_name}__{call_idx}"
        for i in range(1, n_stages + 1):
            stage_input = input_expr if i == 1 else f"{prefix}_{i - 1}"
            stocks.append(DelayStock(
                name=f"{prefix}_{i}",
                input_expr=stage_input,
                delay_time_expr=stage_delay,
            ))

        # Replace this call node with a Name referencing the final stock
        final_name = stocks[-1].name
        # Swap the AST node in-place
        node.func = None  # type: ignore[assignment]  # sentinel for replacement
        node._replace_name = final_name  # type: ignore[attr-defined]

        all_delay_stocks.extend(stocks)
        call_idx += 1

    # Rebuild equation string with replacements
    # Use regex-based replacement since AST manipulation is complex
    rewritten = equation
    for idx, (raw_func_name, args, start, end) in enumerate(calls_sorted):
        prefix = f"__delay__{var_name}__{len(calls_sorted) - 1 - idx}"
        normalized = _SMOOTH_TO_DELAY.get(raw_func_name, raw_func_name)
        if normalized == "delayn" and len(args) >= 3:
            n_stages = int(ast.literal_eval(args[2]))
        elif normalized == "delay3":
            n_stages = 3
        else:
            n_stages = 1
        final_name = f"{prefix}_{n_stages}"
        # Replace the call substring
        rewritten = rewritten[:start] + final_name + rewritten[end:]

    return rewritten, all_delay_stocks


def _find_delay_fixed_calls(equation: str) -> list[tuple[list[str], int, int]]:
    """Find delay_fixed() calls in an equation.

    Returns list of (arg_sources, start_offset, end_offset).
    """
    try:
        tree = ast.parse(equation, mode="eval")
    except SyntaxError:
        return []

    results: list[tuple[list[str], int, int]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        if not isinstance(node.func, ast.Name):
            continue
        if node.func.id != "delay_fixed":
            continue
        arg_sources = [_ast_to_source(arg) for arg in node.args]
        results.append((arg_sources, node.col_offset, node.end_col_offset or 0))
    return results


def _expand_delay_fixed(
    var_name: str,
    equation: str,
) -> tuple[str, list[DelayFixedSpec]]:
    """Expand delay_fixed() calls into DelayFixedSpec entries.

    delay_fixed(input, delay_time, initial_value)

    Returns (rewritten_equation, delay_fixed_specs).
    """
    calls = _find_delay_fixed_calls(equation)
    if not calls:
        return equation, []

    specs: list[DelayFixedSpec] = []
    # Process in reverse offset order
    calls_sorted = sorted(calls, key=lambda c: c[1], reverse=True)

    rewritten = equation
    for idx, (args, start, end) in enumerate(calls_sorted):
        if len(args) < 3:
            continue
        spec_name = f"__delayfixed__{var_name}__{idx}"
        specs.append(DelayFixedSpec(
            name=spec_name,
            input_expr=args[0],
            delay_time_expr=args[1],
            initial_expr=args[2],
        ))
        rewritten = rewritten[:start] + spec_name + rewritten[end:]

    return rewritten, specs


def translate_model(model: ModelDocument) -> ExecutableModel:
    # Auto-derive stock equations from flow_link edges
    derived_equations = _derive_stock_equations(model)

    stock_nodes: list[StockNode] = []
    aux_nodes: list[AuxNode] = []
    flow_nodes: list[FlowNode] = []
    lookup_nodes: list[LookupNode] = []
    node_by_name: dict[str, object] = {}
    for node in model.nodes:
        if isinstance(node, StockNode):
            if node.id in derived_equations:
                node = node.model_copy(update={"equation": derived_equations[node.id]})
            node_by_name[node.name] = node
            stock_nodes.append(node)
        elif isinstance(node, AuxNode):
            node_by_name[node.name] = node
            aux_nodes.append(node)
        elif isinstance(node, FlowNode):
            node_by_name[node.name] = node
            flow_nodes.append(node)
        elif isinstance(node, LookupNode):
            node_by_name[node.name] = node
            lookup_nodes.append(node)

    # Expand delay function calls in transient equations
    all_delay_stocks: list[DelayStock] = []
    all_delay_fixed: list[DelayFixedSpec] = []

    for i, node in enumerate(aux_nodes):
        rewritten, delay_stocks = _expand_delays(node.name, node.equation)
        if delay_stocks:
            aux_nodes[i] = node.model_copy(update={"equation": rewritten})
            node_by_name[node.name] = aux_nodes[i]
            all_delay_stocks.extend(delay_stocks)
        rewritten2, df_specs = _expand_delay_fixed(aux_nodes[i].name, aux_nodes[i].equation)
        if df_specs:
            aux_nodes[i] = aux_nodes[i].model_copy(update={"equation": rewritten2})
            node_by_name[aux_nodes[i].name] = aux_nodes[i]
            all_delay_fixed.extend(df_specs)

    for i, node in enumerate(flow_nodes):
        rewritten, delay_stocks = _expand_delays(node.name, node.equation)
        if delay_stocks:
            flow_nodes[i] = node.model_copy(update={"equation": rewritten})
            node_by_name[node.name] = flow_nodes[i]
            all_delay_stocks.extend(delay_stocks)
        rewritten2, df_specs = _expand_delay_fixed(flow_nodes[i].name, flow_nodes[i].equation)
        if df_specs:
            flow_nodes[i] = flow_nodes[i].model_copy(update={"equation": rewritten2})
            node_by_name[flow_nodes[i].name] = flow_nodes[i]
            all_delay_fixed.extend(df_specs)

    transient_order = topological_order_for_transients(model)
    outputs = model.outputs or [n.name for n in stock_nodes]
    return ExecutableModel(
        stock_nodes=stock_nodes,
        aux_nodes=aux_nodes,
        flow_nodes=flow_nodes,
        lookup_nodes=lookup_nodes,
        node_by_name=node_by_name,
        transient_order=transient_order,
        outputs=outputs,
        delay_stocks=all_delay_stocks,
        delay_fixed_specs=all_delay_fixed,
    )
